# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# === Basic configuration ===

# Your application's name
appname: "myhomepage"

liteblog:
  title: "Alexis Sukrieh"
  description: "Personal site of Alexis Sukrieh, CTO of Weborama, Perl Hacker and Calisthenics Enthusiast"
  tags: 
    - "Alexis Sukrieh"
    - "Perl"
    - "Calisthenics"
    - "Weborama"
    - "CTO"
  logo: "/images/avatar.jpg"
  base_url: "https://alexissukrieh.com"

  navigation:
    - label: "Home"
      link: "/"
    - label: "Linkedin"
      link: "https://fr.linkedin.com/in/asukrieh"
    - label: "Strava"
      link: "https://www.strava.com/athletes/6777031"
    - label: "GitHub"
      link: "https://github.com/sukria"
    - label: "Dev Blog"
      link: "/dev"
  feature:
    highlight: 1
  widgets:
    - name: "activities"
      params: 
        source: "liteblog/activities.yml"
    - name: "blog"
      params:
        title: "Read my Stories"
        mount: "/"
        root: "liteblog/articles"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "liteblog"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# === Engines ===
#
# NOTE: All the engine configurations need to be under a single "engines:"
# key.  If you uncomment engine configurations below, make sure to delete
# all "engines:" lines except the first.  Otherwise, only the last
# "engines:" block will take effect.

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
template: template_toolkit
