version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=$DANCER_HOST
      - VIRTUAL_PORT=$DANCER_PORT
      - LETSENCRYPT_HOST=$DANCER_HOST
      - LETSENCRYPT_EMAIL=$DANCER_EMAIL
      - DANCER_ENVIRONMENT=production
    ports:
      - "5000:80"
    volumes:
      - ${APP_ROOT}/config.yml:/app/config.yml
      - ${APP_ROOT}/public:/app/public
      - ${APP_ROOT}/environments:/app/environments

networks:
  default:
     external:
       name: $NETWORK
