---
title: "La république au tapis"
image: "allin.jpg"
excerpt: "Il est aux abois, abandonné par le jeu qu’il croyait maîtriser. Presque lessivé par ses pertes, il voit la partie lui échapper. Pas possible, pas acceptable.  Son égo s’enflamme, une impulsion embrase tout son système nerveux, il pousse ses derniers billets à deux mains, l’œil allumé par l’adrénaline du joueur. Il dit : « Tapis », un sourire carnassier aux lèvres, sûr de créer la surprise une fois de plus.  Il joue la France parce que perdre la face, c’est pire que de plonger le pays dans le chaos. Et puis, il ne peut pas perdre. Pas possible." 
tags:
  - france
  - Macron
  - RN
  - dissolution

